BEGIN;

DROP VIEW IF EXISTS switch_latest_status;
DROP VIEW IF EXISTS switch_latest_electrical;
DROP VIEW IF EXISTS switch_control_history;
DROP VIEW IF EXISTS switch_status_measurements;
DROP VIEW IF EXISTS switch_electrical_measurements;
DROP VIEW IF EXISTS lighting_latest_status;
DROP VIEW IF EXISTS lighting_latest_electrical;
DROP VIEW IF EXISTS lighting_control_history;
DROP VIEW IF EXISTS lighting_status_measurements;
DROP VIEW IF EXISTS lighting_electrical_measurements;
DROP VIEW IF EXISTS air_conditioner_latest_status;
DROP VIEW IF EXISTS air_conditioner_latest_electrical;
DROP VIEW IF EXISTS air_conditioner_control_history;
DROP VIEW IF EXISTS air_conditioner_status_measurements;
DROP VIEW IF EXISTS air_conditioner_electrical_measurements;
DROP VIEW IF EXISTS thermostat_latest_status;
DROP VIEW IF EXISTS thermostat_latest_electrical;
DROP VIEW IF EXISTS thermostat_control_history;
DROP VIEW IF EXISTS thermostat_status_measurements;
DROP VIEW IF EXISTS thermostat_electrical_measurements;
DROP VIEW IF EXISTS latest_device_status;
DROP VIEW IF EXISTS latest_electrical_measurement;

CREATE TABLE switch_status_measurements (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  measured_at timestamptz NOT NULL DEFAULT now(),
  device_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  manufacturer_code text,
  imei varchar(255) NOT NULL,
  switch_1 boolean,
  switch_2 boolean,
  switch_3 boolean,
  breaker_state text,
  trip_state boolean,
  trip_reason text,
  alarm_code text,
  online boolean,
  state jsonb NOT NULL DEFAULT '{}'::jsonb,
  source varchar(32) NOT NULL DEFAULT 'mqtt',
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, measured_at)
);

CREATE TABLE lighting_status_measurements (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  measured_at timestamptz NOT NULL DEFAULT now(),
  device_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  manufacturer_code text,
  imei varchar(255) NOT NULL,
  switch_1 boolean,
  switch_2 boolean,
  switch_3 boolean,
  brightness double precision,
  color_temperature double precision,
  illuminance double precision,
  scene_code text,
  channel_states jsonb,
  alarm_code text,
  online boolean,
  state jsonb NOT NULL DEFAULT '{}'::jsonb,
  source varchar(32) NOT NULL DEFAULT 'mqtt',
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, measured_at)
);

CREATE TABLE air_conditioner_status_measurements (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  measured_at timestamptz NOT NULL DEFAULT now(),
  device_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  manufacturer_code text,
  imei varchar(255) NOT NULL,
  power_status boolean,
  mode text,
  fan_speed text,
  target_temperature double precision,
  current_temperature double precision,
  humidity double precision,
  compressor_state boolean,
  indoor_fan_state boolean,
  outdoor_fan_state boolean,
  valve_state text,
  error_code text,
  alarm_code text,
  online boolean,
  state jsonb NOT NULL DEFAULT '{}'::jsonb,
  source varchar(32) NOT NULL DEFAULT 'mqtt',
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, measured_at)
);

CREATE TABLE thermostat_status_measurements (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  measured_at timestamptz NOT NULL DEFAULT now(),
  device_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  manufacturer_code text,
  imei varchar(255) NOT NULL,
  power_status boolean,
  mode text,
  fan_speed text,
  target_temperature double precision,
  current_temperature double precision,
  humidity double precision,
  valve_state text,
  relay_state boolean,
  key_lock boolean,
  battery_level double precision,
  error_code text,
  online boolean,
  state jsonb NOT NULL DEFAULT '{}'::jsonb,
  source varchar(32) NOT NULL DEFAULT 'mqtt',
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, measured_at)
);

CREATE TABLE switch_electrical_measurements (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  measured_at timestamptz NOT NULL DEFAULT now(),
  device_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  manufacturer_code text,
  imei varchar(255) NOT NULL,
  phase_type varchar(32) NOT NULL DEFAULT 'single_phase',
  voltage double precision, current double precision, power double precision,
  active_power double precision, reactive_power double precision, apparent_power double precision,
  power_factor double precision, frequency double precision,
  energy double precision, import_energy double precision, export_energy double precision,
  reactive_import_energy double precision, reactive_export_energy double precision,
  leakage_current double precision, temperature double precision,
  voltage_a double precision, voltage_b double precision, voltage_c double precision,
  current_a double precision, current_b double precision, current_c double precision, neutral_current double precision,
  power_a double precision, power_b double precision, power_c double precision,
  reactive_power_a double precision, reactive_power_b double precision, reactive_power_c double precision,
  apparent_power_a double precision, apparent_power_b double precision, apparent_power_c double precision,
  power_factor_a double precision, power_factor_b double precision, power_factor_c double precision,
  temperature_a double precision, temperature_b double precision, temperature_c double precision,
  cabinet_temperature double precision,
  voltage_thd double precision, voltage_thd_a double precision, voltage_thd_b double precision, voltage_thd_c double precision,
  current_thd double precision, current_thd_a double precision, current_thd_b double precision, current_thd_c double precision,
  demand double precision, max_demand double precision,
  extra_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, measured_at)
);

CREATE TABLE lighting_electrical_measurements (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  measured_at timestamptz NOT NULL DEFAULT now(),
  device_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  manufacturer_code text,
  imei varchar(255) NOT NULL,
  phase_type varchar(32) NOT NULL DEFAULT 'single_phase',
  voltage double precision, current double precision, power double precision,
  active_power double precision, reactive_power double precision, apparent_power double precision,
  power_factor double precision, frequency double precision,
  energy double precision, import_energy double precision, export_energy double precision,
  reactive_import_energy double precision, reactive_export_energy double precision,
  leakage_current double precision, temperature double precision,
  voltage_a double precision, voltage_b double precision, voltage_c double precision,
  current_a double precision, current_b double precision, current_c double precision, neutral_current double precision,
  power_a double precision, power_b double precision, power_c double precision,
  reactive_power_a double precision, reactive_power_b double precision, reactive_power_c double precision,
  apparent_power_a double precision, apparent_power_b double precision, apparent_power_c double precision,
  power_factor_a double precision, power_factor_b double precision, power_factor_c double precision,
  temperature_a double precision, temperature_b double precision, temperature_c double precision,
  cabinet_temperature double precision,
  voltage_thd double precision, voltage_thd_a double precision, voltage_thd_b double precision, voltage_thd_c double precision,
  current_thd double precision, current_thd_a double precision, current_thd_b double precision, current_thd_c double precision,
  demand double precision, max_demand double precision,
  channel_count integer, channel_measurements jsonb,
  dimming_power double precision, driver_temperature double precision,
  extra_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, measured_at)
);

CREATE TABLE air_conditioner_electrical_measurements (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  measured_at timestamptz NOT NULL DEFAULT now(),
  device_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  manufacturer_code text,
  imei varchar(255) NOT NULL,
  phase_type varchar(32) NOT NULL DEFAULT 'single_phase',
  voltage double precision, current double precision, power double precision,
  active_power double precision, reactive_power double precision, apparent_power double precision,
  power_factor double precision, frequency double precision,
  energy double precision, import_energy double precision, export_energy double precision,
  reactive_import_energy double precision, reactive_export_energy double precision,
  leakage_current double precision, temperature double precision,
  voltage_a double precision, voltage_b double precision, voltage_c double precision,
  current_a double precision, current_b double precision, current_c double precision, neutral_current double precision,
  power_a double precision, power_b double precision, power_c double precision,
  reactive_power_a double precision, reactive_power_b double precision, reactive_power_c double precision,
  apparent_power_a double precision, apparent_power_b double precision, apparent_power_c double precision,
  power_factor_a double precision, power_factor_b double precision, power_factor_c double precision,
  temperature_a double precision, temperature_b double precision, temperature_c double precision,
  cabinet_temperature double precision,
  voltage_thd double precision, voltage_thd_a double precision, voltage_thd_b double precision, voltage_thd_c double precision,
  current_thd double precision, current_thd_a double precision, current_thd_b double precision, current_thd_c double precision,
  demand double precision, max_demand double precision,
  compressor_current double precision, compressor_power double precision, compressor_temperature double precision,
  indoor_fan_current double precision, indoor_fan_power double precision,
  outdoor_fan_current double precision, outdoor_fan_power double precision,
  heating_energy double precision, cooling_energy double precision, standby_power double precision,
  evaporator_temperature double precision, condenser_temperature double precision,
  suction_pressure double precision, discharge_pressure double precision,
  extra_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, measured_at)
);

CREATE TABLE thermostat_electrical_measurements (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  measured_at timestamptz NOT NULL DEFAULT now(),
  device_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  manufacturer_code text,
  imei varchar(255) NOT NULL,
  phase_type varchar(32) NOT NULL DEFAULT 'single_phase',
  voltage double precision, current double precision, power double precision,
  active_power double precision, reactive_power double precision, apparent_power double precision,
  power_factor double precision, frequency double precision,
  energy double precision, import_energy double precision, export_energy double precision,
  reactive_import_energy double precision, reactive_export_energy double precision,
  leakage_current double precision, temperature double precision,
  voltage_a double precision, voltage_b double precision, voltage_c double precision,
  current_a double precision, current_b double precision, current_c double precision, neutral_current double precision,
  power_a double precision, power_b double precision, power_c double precision,
  reactive_power_a double precision, reactive_power_b double precision, reactive_power_c double precision,
  apparent_power_a double precision, apparent_power_b double precision, apparent_power_c double precision,
  power_factor_a double precision, power_factor_b double precision, power_factor_c double precision,
  temperature_a double precision, temperature_b double precision, temperature_c double precision,
  cabinet_temperature double precision,
  voltage_thd double precision, voltage_thd_a double precision, voltage_thd_b double precision, voltage_thd_c double precision,
  current_thd double precision, current_thd_a double precision, current_thd_b double precision, current_thd_c double precision,
  demand double precision, max_demand double precision,
  relay_current double precision, relay_power double precision,
  fan_current double precision, fan_power double precision,
  valve_current double precision, valve_power double precision,
  standby_power double precision, battery_voltage double precision, battery_level double precision,
  extra_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, measured_at)
);

DO $$
DECLARE
  module_name text;
BEGIN
  FOREACH module_name IN ARRAY ARRAY['switch', 'lighting', 'air_conditioner', 'thermostat']
  LOOP
    EXECUTE format(
      'CREATE TABLE %I_control_logs (
         id bigint GENERATED BY DEFAULT AS IDENTITY,
         created_at timestamptz NOT NULL DEFAULT now(),
         tenant_id uuid NOT NULL,
         device_id uuid NOT NULL,
         action varchar(128) NOT NULL,
         command jsonb NOT NULL DEFAULT ''{}''::jsonb,
         encoded_payload jsonb,
         mqtt_topic text,
         status varchar(24) NOT NULL CHECK (status IN (''sent'', ''failed'')),
         error_message text,
         user_id uuid,
         control_source varchar(32) NOT NULL DEFAULT ''manual'',
         PRIMARY KEY (id, created_at)
       )',
      module_name
    );
  END LOOP;
END $$;

SELECT create_hypertable('switch_status_measurements', by_range('measured_at', INTERVAL '7 days'));
SELECT create_hypertable('lighting_status_measurements', by_range('measured_at', INTERVAL '7 days'));
SELECT create_hypertable('air_conditioner_status_measurements', by_range('measured_at', INTERVAL '7 days'));
SELECT create_hypertable('thermostat_status_measurements', by_range('measured_at', INTERVAL '7 days'));
SELECT create_hypertable('switch_electrical_measurements', by_range('measured_at', INTERVAL '7 days'));
SELECT create_hypertable('lighting_electrical_measurements', by_range('measured_at', INTERVAL '7 days'));
SELECT create_hypertable('air_conditioner_electrical_measurements', by_range('measured_at', INTERVAL '7 days'));
SELECT create_hypertable('thermostat_electrical_measurements', by_range('measured_at', INTERVAL '7 days'));
SELECT create_hypertable('switch_control_logs', by_range('created_at', INTERVAL '30 days'));
SELECT create_hypertable('lighting_control_logs', by_range('created_at', INTERVAL '30 days'));
SELECT create_hypertable('air_conditioner_control_logs', by_range('created_at', INTERVAL '30 days'));
SELECT create_hypertable('thermostat_control_logs', by_range('created_at', INTERVAL '30 days'));

DO $$
DECLARE
  module_name text;
BEGIN
  FOREACH module_name IN ARRAY ARRAY['switch', 'lighting', 'air_conditioner', 'thermostat']
  LOOP
    EXECUTE format('CREATE INDEX idx_%I_status_device_time ON %I_status_measurements (device_id, measured_at DESC)', module_name, module_name);
    EXECUTE format('CREATE INDEX idx_%I_status_tenant_time ON %I_status_measurements (tenant_id, measured_at DESC)', module_name, module_name);
    EXECUTE format('CREATE INDEX idx_%I_electrical_device_time ON %I_electrical_measurements (device_id, measured_at DESC)', module_name, module_name);
    EXECUTE format('CREATE INDEX idx_%I_electrical_tenant_time ON %I_electrical_measurements (tenant_id, measured_at DESC)', module_name, module_name);
    EXECUTE format('CREATE INDEX idx_%I_control_device_time ON %I_control_logs (device_id, created_at DESC)', module_name, module_name);
    EXECUTE format('CREATE INDEX idx_%I_control_tenant_time ON %I_control_logs (tenant_id, created_at DESC)', module_name, module_name);
  END LOOP;
END $$;

CREATE OR REPLACE FUNCTION enforce_specific_control_module_membership()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM control_device_assignments assignment
    WHERE assignment.device_id = NEW.device_id
      AND assignment.tenant_id = NEW.tenant_id
      AND assignment.module_type = TG_ARGV[0]
      AND assignment.is_active = true
  ) THEN
    RAISE EXCEPTION 'device % is not active in control module %', NEW.device_id, TG_ARGV[0]
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

INSERT INTO switch_status_measurements (
  measured_at, device_id, tenant_id, manufacturer_code, imei,
  switch_1, switch_2, switch_3, state, source, raw_payload, created_at
)
SELECT measured_at, device_id, tenant_id, manufacturer_code, imei,
       CASE lower(COALESCE(state->>'switch_1', state->>'key1')) WHEN 'true' THEN true WHEN 'false' THEN false ELSE NULL END,
       CASE lower(COALESCE(state->>'switch_2', state->>'key2')) WHEN 'true' THEN true WHEN 'false' THEN false ELSE NULL END,
       CASE lower(COALESCE(state->>'switch_3', state->>'key3')) WHEN 'true' THEN true WHEN 'false' THEN false ELSE NULL END,
       state, source, raw_payload, created_at
FROM device_status_measurements
WHERE module_type = 'switch';

INSERT INTO lighting_status_measurements (
  measured_at, device_id, tenant_id, manufacturer_code, imei,
  switch_1, switch_2, switch_3, state, source, raw_payload, created_at
)
SELECT measured_at, device_id, tenant_id, manufacturer_code, imei,
       CASE lower(COALESCE(state->>'switch_1', state->>'key1')) WHEN 'true' THEN true WHEN 'false' THEN false ELSE NULL END,
       CASE lower(COALESCE(state->>'switch_2', state->>'key2')) WHEN 'true' THEN true WHEN 'false' THEN false ELSE NULL END,
       CASE lower(COALESCE(state->>'switch_3', state->>'key3')) WHEN 'true' THEN true WHEN 'false' THEN false ELSE NULL END,
       state, source, raw_payload, created_at
FROM device_status_measurements
WHERE module_type = 'lighting';

INSERT INTO air_conditioner_status_measurements (
  measured_at, device_id, tenant_id, manufacturer_code, imei,
  power_status, mode, fan_speed, target_temperature, current_temperature, humidity,
  state, source, raw_payload, created_at
)
SELECT measured_at, device_id, tenant_id, manufacturer_code, imei,
       CASE lower(COALESCE(state->>'power_status', state->>'power_state')) WHEN 'true' THEN true WHEN 'false' THEN false ELSE NULL END,
       COALESCE(state->>'mode', state->>'ac_mode'),
       state->>'fan_speed',
       CASE WHEN COALESCE(state->>'target_temperature', state->>'target_temp') ~ '^-?[0-9]+([.][0-9]+)?$'
         THEN COALESCE(state->>'target_temperature', state->>'target_temp')::double precision END,
       CASE WHEN COALESCE(state->>'current_temperature', state->>'current_temp') ~ '^-?[0-9]+([.][0-9]+)?$'
         THEN COALESCE(state->>'current_temperature', state->>'current_temp')::double precision END,
       CASE WHEN state->>'humidity' ~ '^-?[0-9]+([.][0-9]+)?$' THEN (state->>'humidity')::double precision END,
       state, source, raw_payload, created_at
FROM device_status_measurements
WHERE module_type = 'air_conditioner';

INSERT INTO thermostat_status_measurements (
  measured_at, device_id, tenant_id, manufacturer_code, imei,
  power_status, mode, fan_speed, target_temperature, current_temperature, humidity,
  state, source, raw_payload, created_at
)
SELECT measured_at, device_id, tenant_id, manufacturer_code, imei,
       CASE lower(state->>'power_status') WHEN 'true' THEN true WHEN 'false' THEN false ELSE NULL END,
       COALESCE(state->>'mode', state->>'ac_mode'),
       state->>'fan_speed',
       CASE WHEN COALESCE(state->>'target_temperature', state->>'target_temp') ~ '^-?[0-9]+([.][0-9]+)?$'
         THEN COALESCE(state->>'target_temperature', state->>'target_temp')::double precision END,
       CASE WHEN COALESCE(state->>'current_temperature', state->>'current_temp') ~ '^-?[0-9]+([.][0-9]+)?$'
         THEN COALESCE(state->>'current_temperature', state->>'current_temp')::double precision END,
       CASE WHEN state->>'humidity' ~ '^-?[0-9]+([.][0-9]+)?$' THEN (state->>'humidity')::double precision END,
       state, source, raw_payload, created_at
FROM device_status_measurements
WHERE module_type = 'thermostat';

INSERT INTO switch_electrical_measurements (
  measured_at, device_id, tenant_id, manufacturer_code, imei, phase_type,
  voltage, current, power, energy,
  voltage_a, voltage_b, voltage_c, current_a, current_b, current_c,
  power_a, power_b, power_c, power_factor, power_factor_a, power_factor_b, power_factor_c,
  frequency, leakage_current, temperature, temperature_a, temperature_b, temperature_c,
  raw_payload, created_at
)
SELECT measured_at, device_id, tenant_id, manufacturer_code, imei, phase_type,
       voltage, current, power, energy,
       voltage_a, voltage_b, voltage_c, current_a, current_b, current_c,
       power_a, power_b, power_c, power_factor, power_factor_a, power_factor_b, power_factor_c,
       frequency, leakage_current, temperature, temperature_a, temperature_b, temperature_c,
       raw_payload, created_at
FROM electrical_measurements WHERE module_type = 'switch';

INSERT INTO lighting_electrical_measurements (
  measured_at, device_id, tenant_id, manufacturer_code, imei, phase_type,
  voltage, current, power, energy,
  voltage_a, voltage_b, voltage_c, current_a, current_b, current_c,
  power_a, power_b, power_c, power_factor, power_factor_a, power_factor_b, power_factor_c,
  frequency, leakage_current, temperature, temperature_a, temperature_b, temperature_c,
  raw_payload, created_at
)
SELECT measured_at, device_id, tenant_id, manufacturer_code, imei, phase_type,
       voltage, current, power, energy,
       voltage_a, voltage_b, voltage_c, current_a, current_b, current_c,
       power_a, power_b, power_c, power_factor, power_factor_a, power_factor_b, power_factor_c,
       frequency, leakage_current, temperature, temperature_a, temperature_b, temperature_c,
       raw_payload, created_at
FROM electrical_measurements WHERE module_type = 'lighting';

INSERT INTO air_conditioner_electrical_measurements (
  measured_at, device_id, tenant_id, manufacturer_code, imei, phase_type,
  voltage, current, power, energy, power_factor, frequency, leakage_current, temperature,
  raw_payload, created_at
)
SELECT measured_at, device_id, tenant_id, manufacturer_code, imei, phase_type,
       voltage, current, power, energy, power_factor, frequency, leakage_current, temperature,
       raw_payload, created_at
FROM electrical_measurements WHERE module_type = 'air_conditioner';

INSERT INTO thermostat_electrical_measurements (
  measured_at, device_id, tenant_id, manufacturer_code, imei, phase_type,
  voltage, current, power, energy, power_factor, frequency, leakage_current, temperature,
  raw_payload, created_at
)
SELECT measured_at, device_id, tenant_id, manufacturer_code, imei, phase_type,
       voltage, current, power, energy, power_factor, frequency, leakage_current, temperature,
       raw_payload, created_at
FROM electrical_measurements WHERE module_type = 'thermostat';

INSERT INTO switch_control_logs (
  created_at, tenant_id, device_id, action, command, encoded_payload,
  mqtt_topic, status, error_message, user_id, control_source
)
SELECT created_at, tenant_id, device_id, action, command, encoded_payload,
       mqtt_topic, status, error_message, user_id, control_source
FROM device_control_logs WHERE module_type = 'switch';

INSERT INTO lighting_control_logs (
  created_at, tenant_id, device_id, action, command, encoded_payload,
  mqtt_topic, status, error_message, user_id, control_source
)
SELECT created_at, tenant_id, device_id, action, command, encoded_payload,
       mqtt_topic, status, error_message, user_id, control_source
FROM device_control_logs WHERE module_type = 'lighting';

INSERT INTO air_conditioner_control_logs (
  created_at, tenant_id, device_id, action, command, encoded_payload,
  mqtt_topic, status, error_message, user_id, control_source
)
SELECT created_at, tenant_id, device_id, action, command, encoded_payload,
       mqtt_topic, status, error_message, user_id, control_source
FROM device_control_logs WHERE module_type = 'air_conditioner';

INSERT INTO thermostat_control_logs (
  created_at, tenant_id, device_id, action, command, encoded_payload,
  mqtt_topic, status, error_message, user_id, control_source
)
SELECT created_at, tenant_id, device_id, action, command, encoded_payload,
       mqtt_topic, status, error_message, user_id, control_source
FROM device_control_logs WHERE module_type = 'thermostat';

DO $$
DECLARE
  module_name text;
  table_suffix text;
BEGIN
  FOREACH module_name IN ARRAY ARRAY['switch', 'lighting', 'air_conditioner', 'thermostat']
  LOOP
    FOREACH table_suffix IN ARRAY ARRAY['status_measurements', 'electrical_measurements', 'control_logs']
    LOOP
      EXECUTE format(
        'CREATE TRIGGER trg_%I_%I_membership
         BEFORE INSERT OR UPDATE OF device_id, tenant_id ON %I_%I
         FOR EACH ROW EXECUTE FUNCTION enforce_specific_control_module_membership(%L)',
        module_name, table_suffix, module_name, table_suffix, module_name
      );
    END LOOP;
  END LOOP;
END $$;

DROP TRIGGER IF EXISTS trg_status_module_membership ON device_status_measurements;
DROP TRIGGER IF EXISTS trg_electrical_module_membership ON electrical_measurements;
DROP TRIGGER IF EXISTS trg_control_log_module_membership ON device_control_logs;

ALTER TABLE device_status_measurements RENAME TO legacy_unified_device_status_measurements;
ALTER TABLE electrical_measurements RENAME TO legacy_unified_electrical_measurements;
ALTER TABLE device_control_logs RENAME TO legacy_unified_device_control_logs;

DO $$
DECLARE
  module_name text;
BEGIN
  FOREACH module_name IN ARRAY ARRAY['switch', 'lighting', 'air_conditioner', 'thermostat']
  LOOP
    EXECUTE format(
      'CREATE VIEW %I_latest_status AS
       SELECT DISTINCT ON (device_id) * FROM %I_status_measurements
       ORDER BY device_id, measured_at DESC, id DESC',
      module_name, module_name
    );
    EXECUTE format(
      'CREATE VIEW %I_latest_electrical AS
       SELECT DISTINCT ON (device_id) * FROM %I_electrical_measurements
       ORDER BY device_id, measured_at DESC, id DESC',
      module_name, module_name
    );
    EXECUTE format(
      'CREATE VIEW %I_control_history AS SELECT * FROM %I_control_logs',
      module_name, module_name
    );
  END LOOP;
END $$;

UPDATE database_table_lifecycle
SET table_name = 'legacy_unified_device_status_measurements',
    display_name = '旧统一设备状态时序数据',
    lifecycle_status = 'pending_delete',
    owner_module = 'legacy_unified_telemetry',
    reason = '已迁移到四个模块独立状态时序表，保留等待核对后删除',
    marked_at = now()
WHERE table_schema = 'public' AND table_name = 'device_status_measurements';

UPDATE database_table_lifecycle
SET table_name = 'legacy_unified_electrical_measurements',
    display_name = '旧统一电气时序数据',
    lifecycle_status = 'pending_delete',
    owner_module = 'legacy_unified_telemetry',
    reason = '已改为四个模块独立电气时序表，原表为空，保留等待核对后删除',
    marked_at = now()
WHERE table_schema = 'public' AND table_name = 'electrical_measurements';

UPDATE database_table_lifecycle
SET table_name = 'legacy_unified_device_control_logs',
    display_name = '旧统一设备控制记录',
    lifecycle_status = 'pending_delete',
    owner_module = 'legacy_unified_telemetry',
    reason = '已迁移到四个模块独立控制记录时序表，保留等待核对后删除',
    marked_at = now()
WHERE table_schema = 'public' AND table_name = 'device_control_logs';

INSERT INTO database_table_lifecycle (
  table_schema, table_name, display_name, lifecycle_status, owner_module, reason
)
SELECT 'public', module_name || '_status_measurements', chinese_name || '状态时序数据',
       'active', module_name, chinese_name || '模块专用状态 hypertable'
FROM (VALUES
  ('switch', '开关控制'), ('lighting', '照明控制'),
  ('air_conditioner', '分散空调控制'), ('thermostat', '温控控制')
) modules(module_name, chinese_name)
UNION ALL
SELECT 'public', module_name || '_electrical_measurements', chinese_name || '电气时序数据',
       'active', module_name, chinese_name || '模块专用电气 hypertable，支持 extra_metrics 扩展字段'
FROM (VALUES
  ('switch', '开关控制'), ('lighting', '照明控制'),
  ('air_conditioner', '分散空调控制'), ('thermostat', '温控控制')
) modules(module_name, chinese_name)
UNION ALL
SELECT 'public', module_name || '_control_logs', chinese_name || '控制记录',
       'active', module_name, chinese_name || '模块专用控制记录 hypertable'
FROM (VALUES
  ('switch', '开关控制'), ('lighting', '照明控制'),
  ('air_conditioner', '分散空调控制'), ('thermostat', '温控控制')
) modules(module_name, chinese_name);

DO $$
DECLARE
  table_record record;
BEGIN
  FOR table_record IN
    SELECT table_schema, table_name, display_name, reason
    FROM database_table_lifecycle
    WHERE table_name LIKE ANY (ARRAY[
      'switch_%', 'lighting_%', 'air_conditioner_%', 'thermostat_%', 'legacy_unified_%'
    ])
      AND to_regclass(format('%I.%I', table_schema, table_name)) IS NOT NULL
  LOOP
    EXECUTE format(
      'COMMENT ON TABLE %I.%I IS %L',
      table_record.table_schema,
      table_record.table_name,
      format('中文名称：%s。%s', table_record.display_name, table_record.reason)
    );
  END LOOP;
END $$;

COMMIT;
