BEGIN;

CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE IF NOT EXISTS control_device_assignments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  device_id uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  module_type varchar(32) NOT NULL CHECK (module_type IN ('switch', 'lighting', 'air_conditioner', 'thermostat')),
  subtype varchar(64),
  display_order integer NOT NULL DEFAULT 0,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (device_id, module_type)
);

CREATE INDEX IF NOT EXISTS idx_control_assignments_tenant_module
  ON control_device_assignments (tenant_id, module_type, is_active, display_order);

CREATE TABLE IF NOT EXISTS device_status_measurements (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  measured_at timestamptz NOT NULL DEFAULT now(),
  device_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  module_type varchar(32) NOT NULL CHECK (module_type IN ('switch', 'lighting', 'air_conditioner', 'thermostat')),
  manufacturer_code text,
  imei varchar(255) NOT NULL,
  state jsonb NOT NULL DEFAULT '{}'::jsonb,
  source varchar(32) NOT NULL DEFAULT 'mqtt' CHECK (source IN ('mqtt', 'device_response', 'manual_import')),
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, measured_at)
);

SELECT create_hypertable(
  'device_status_measurements',
  by_range('measured_at', INTERVAL '7 days'),
  if_not_exists => true
);

CREATE INDEX IF NOT EXISTS idx_status_device_module_time
  ON device_status_measurements (device_id, module_type, measured_at DESC);
CREATE INDEX IF NOT EXISTS idx_status_tenant_module_time
  ON device_status_measurements (tenant_id, module_type, measured_at DESC);
CREATE INDEX IF NOT EXISTS idx_status_imei_module_time
  ON device_status_measurements (imei, module_type, measured_at DESC);

CREATE TABLE IF NOT EXISTS electrical_measurements (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  measured_at timestamptz NOT NULL DEFAULT now(),
  device_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  module_type varchar(32) NOT NULL CHECK (module_type IN ('switch', 'lighting', 'air_conditioner', 'thermostat')),
  manufacturer_code text,
  imei varchar(255) NOT NULL,
  phase_type varchar(32) NOT NULL DEFAULT 'single_phase' CHECK (phase_type IN ('single_phase', 'three_phase')),
  voltage double precision,
  current double precision,
  power double precision,
  energy double precision,
  voltage_a double precision,
  voltage_b double precision,
  voltage_c double precision,
  current_a double precision,
  current_b double precision,
  current_c double precision,
  power_a double precision,
  power_b double precision,
  power_c double precision,
  power_factor double precision,
  power_factor_a double precision,
  power_factor_b double precision,
  power_factor_c double precision,
  frequency double precision,
  leakage_current double precision,
  temperature double precision,
  temperature_a double precision,
  temperature_b double precision,
  temperature_c double precision,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, measured_at)
);

SELECT create_hypertable(
  'electrical_measurements',
  by_range('measured_at', INTERVAL '7 days'),
  if_not_exists => true
);

CREATE INDEX IF NOT EXISTS idx_electrical_device_module_time
  ON electrical_measurements (device_id, module_type, measured_at DESC);
CREATE INDEX IF NOT EXISTS idx_electrical_tenant_module_time
  ON electrical_measurements (tenant_id, module_type, measured_at DESC);
CREATE INDEX IF NOT EXISTS idx_electrical_imei_module_time
  ON electrical_measurements (imei, module_type, measured_at DESC);

CREATE TABLE IF NOT EXISTS device_control_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid NOT NULL,
  device_id uuid NOT NULL,
  module_type varchar(32) NOT NULL CHECK (module_type IN ('switch', 'lighting', 'air_conditioner', 'thermostat')),
  action varchar(128) NOT NULL,
  command jsonb NOT NULL DEFAULT '{}'::jsonb,
  encoded_payload jsonb,
  mqtt_topic text,
  status varchar(24) NOT NULL CHECK (status IN ('sent', 'failed')),
  error_message text,
  user_id uuid,
  control_source varchar(32) NOT NULL DEFAULT 'manual',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_control_logs_device_module_time
  ON device_control_logs (device_id, module_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_control_logs_tenant_module_time
  ON device_control_logs (tenant_id, module_type, created_at DESC);

CREATE OR REPLACE VIEW latest_device_status AS
SELECT DISTINCT ON (device_id, module_type)
  id, measured_at, device_id, tenant_id, module_type, manufacturer_code,
  imei, state, source, raw_payload, created_at
FROM device_status_measurements
ORDER BY device_id, module_type, measured_at DESC, id DESC;

CREATE OR REPLACE VIEW latest_electrical_measurement AS
SELECT DISTINCT ON (device_id, module_type)
  *
FROM electrical_measurements
ORDER BY device_id, module_type, measured_at DESC, id DESC;

INSERT INTO control_device_assignments (
  tenant_id, device_id, module_type, subtype, display_order, config, is_active, created_by, created_at, updated_at
)
SELECT tenant_id, device_id, 'switch', phase_type, COALESCE(display_order, 0),
       jsonb_strip_nulls(jsonb_build_object('strategy_config', strategy_config)),
       is_active, created_by, created_at, updated_at
FROM switch_control
ON CONFLICT (device_id, module_type) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  subtype = EXCLUDED.subtype,
  display_order = EXCLUDED.display_order,
  config = EXCLUDED.config,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO control_device_assignments (
  tenant_id, device_id, module_type, subtype, display_order, config, is_active, created_by, created_at, updated_at
)
SELECT tenant_id, device_id, 'lighting', lighting_type, COALESCE(display_order, 0),
       '{}'::jsonb, is_active, created_by, created_at, updated_at
FROM lighting_control
ON CONFLICT (device_id, module_type) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  subtype = EXCLUDED.subtype,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO control_device_assignments (
  tenant_id, device_id, module_type, display_order, config, is_active, created_by, created_at, updated_at
)
SELECT tenant_id, device_id, 'air_conditioner', COALESCE(display_order, 0),
       jsonb_strip_nulls(jsonb_build_object('strategy_config', strategy_config)),
       is_active, created_by, created_at, updated_at
FROM air_conditioner_control
ON CONFLICT (device_id, module_type) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  display_order = EXCLUDED.display_order,
  config = EXCLUDED.config,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO control_device_assignments (tenant_id, device_id, module_type, subtype, is_active, created_at, updated_at)
SELECT tenant_id, id, 'thermostat', 'air_conditioner_thermostat', true, created_at, updated_at
FROM devices
WHERE is_thermostat = true
ON CONFLICT (device_id, module_type) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  is_active = true,
  updated_at = EXCLUDED.updated_at;

COMMIT;
